[package]
name = "lumi_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lumi_lxr = { path = "../lumi_lxr" }
lumi_psr = { path = "../lumi_psr" }
colored = "2.1.0"
